extraction:
    cpp:
        prepare:
            packages:
              - libxkbcommon-dev
        after_prepare:
          - wget "https://github.com/lkeegan/qt5-static/releases/latest/download/qt5-static-linux.tgz"
          - sudo tar xzvf qt5-static-linux.tgz -C /
          # export path for Qt5 binaries
          - export PATH=$QT5_INSTALL_PREFIX/bin:$PATH
          - qmake -v
          # download pre-compiled static libSBML library
          - cd ext
          - wget "https://github.com/lkeegan/libsbml-static/releases/latest/download/libsbml-static-linux.tgz"
          - mkdir -p libsbml
          - tar xzvf libsbml-static-linux.tgz -C libsbml
          - ls libsbml
          - cd ..
        configure:
            command:
              - mkdir build
              - cd build
              - qmake -Wall -config debug ../spatial-model-editor.pro
        index:
            build_command:
              - cd build
              - make
