language: cpp
env:
  global:
    - QT5_INSTALL_PREFIX="/usr/local/qt5-static"

matrix:
  include:
    ################################################
    # linux release build: gcc 9.1.0 on ubuntu 16.04
    ################################################
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - DEPLOY_FILE="spatial-model-editor"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libxkbcommon-dev
            - jwm
      services: xvfb
      install:
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
        - gcc --version
        - g++ --version
        # start a window manager so the Qt GUI tests can have their focus set
        - "jwm &"
        - sleep 1
      script:
        - bash ci-build.sh "release optimize_full"
        # run tests
        - ./build/test_unity/test_unity -a
        # check dependencies of resulting executable
        - cd build/app
        - ldd spatial-model-editor
    ##############################################################
    # osx release build: xcode 10.3, macOS 10.14 (target >= 10.12)
    ##############################################################
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - DEPLOY_FILE="spatial-model-editor.dmg"
      install:
        - export MACOSX_DEPLOYMENT_TARGET=10.14
      script:
        - bash ci-build.sh "release optimize_full"
        # run tests
        - ./build/test_unity/test_unity.app/Contents/MacOS/test_unity -a
        # check dependencies of resulting executable
        - cd build/app
        - otool -L spatial-model-editor.app/Contents/MacOS/spatial-model-editor
        # NOTE: (does not work): alter plist file manually to require minimum osx 10.12
        # - plutil -p spatial-model-editor.app/Contents/Info.plist
        # - plutil -replace LSMinimumSystemVersion -string "10.12" spatial-model-editor.app/Contents/Info.plist
        # - plutil -p spatial-model-editor.app/Contents/Info.plist
        # package app dir as a .dmg

        # for now just distribute dmg of executable:
        - mkdir spatial-model-editor
        - cp spatial-model-editor.app/Contents/MacOS/spatial-model-editor spatial-model-editor/.
        - hdiutil create spatial-model-editor -fs HFS+ -srcfolder spatial-model-editor
    #####################################################
    # linux code quality build: sonarcloud.io, codecov.io
    #####################################################
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - secure: "Muu56AqHMCZOpCG2d5Byeh6P++9xXKl7otulxdhZCfA1/yTAJM9M67B1ZHo7czEvLKdoVzqCz6aFMnsVvFHUHQDmAtmth/WzdfXZ7OTG7puDIeWRmYqQacpLeF6h9ws3sUr5Bjz9m0guhjbKN/6VIqoyuWLH/J0MwzJN5JKgWitQBeJ15GWjNJN20FLgiYW0vWtQ71dncM6VaLAyH6V/T8jLRNacmCjApAOsS2FuhnSfbL+rY5nRVXPtoy/muwRgpl2Bez8OV6z5nDCaBLxXLgNkC7Y/0OhfzY/t+6wZ4nuDZDJ/4Hn4AyycH1O1ldmfEjw9nHBdqG/0JW2NmvSLojp5NiCUSI1MDmcgqKv6VKdVV2cdn6b7s6YY/8p08pnm+uExHYRkiXPFNeYfoQF3ruYSzFOQXRA+VI3Rg0dMfs4cO+PXCWS/hIAHudG3vaDgOwOnLFaOPjJKGYidmbmu6u4jdvBNFuCkooSYmnO2JCe0LIGgJAwlOEfG51WYD9bewCx+w+NmB+Cow3E4G0DCHomz1XGUhp1DsmjGarU1kDf4PtFLQgLC88h7AQfJtg15mSV6xDcKV+nmuDNS+ifTpQTTSe/w6LqqzcE/EOLaVAtCSe4ACOORW2yBF7DPgUY47ZSkU4iwA7pAOAYDKs37fNHjK8s/TJhM++RZ+21oMME="
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libxkbcommon-dev
            - jwm
        sonarcloud:
          organization: "lkeegan-github"
      services: xvfb
      install:
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
        - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 100
        - gcc --version
        - g++ --version
        - gcov --version
        # start a window manager so the Qt GUI tests can have their focus set
        - "jwm &"
        - sleep 1
      script:
        # build tests & compile executable using sonar-source build wrapper
        - bash ci-build.sh debug make "build-wrapper-linux-x86-64 --out-dir bw-output"
        # run tests
        # make list of "leaks" from system libraries that LeakSanitizer should ignore
        # NB: can also set ASAN_OPTIONS=fast_unwind_on_malloc=0
        # to see more info about any memory leaks from linked libraries
        - echo "leak:libfontconfig.so" > suppr.txt
        - echo "leak:libX11.so" >> suppr.txt
        # generate gcov test coverage data for sonar-source & codecov.io

        # unit tests (i.e. not mainwindow)
        - LSAN_OPTIONS=suppressions=suppr.txt:exitcode=0 ./build/test_unity/test_unity -a "~[mainwindow]"
        - cd build
        - mkdir gcov-unit
        - cd gcov-unit
        - gcov -r -p ../src/*.gcno
        # only want coverage data for src and inc folders
        - mkdir tmp
        - mv *.* tmp
        - cd tmp
        - mv ^#^#inc* ../
        - mv ^#^#src* ../
        - rm *
        - cd ../
        - rmdir tmp
        - ls
        - cd ../
        # upload coverage report to codecov.io
        - bash <(curl --connect-timeout 10 --retry 5 -v -s https://codecov.io/bash) -X gcov -F unit

        # integration tests (i.e. mainwindow)
        - rm src/*.gcda
        - cd ..
        - LSAN_OPTIONS=suppressions=suppr.txt:exitcode=0 ./build/test_unity/test_unity -a "[mainwindow]"
        - cd build
        - mkdir gcov-integration
        - cd gcov-integration
        - gcov -r -p ../src/*.gcno
        # only want coverage data for src and inc folders
        - mkdir tmp
        - mv *.* tmp
        - cd tmp
        - mv ^#^#inc* ../
        - mv ^#^#src* ../
        - rm *
        - cd ../
        - rmdir tmp
        - ls
        - cd ../
        # upload coverage report to codecov.io
        - bash <(curl --connect-timeout 10 --retry 5 -v https://codecov.io/bash) -X gcov -f '!*/gcov-unit/*' -F integration

        # run all tests again for sonarsource
        # inefficient but haven't found a way to combine previous coverage data such that sonarsource can read it
        - rm src/*.gcda
        - cd ..
        - rm units.xml
        - LSAN_OPTIONS=suppressions=suppr.txt:exitcode=0 ./build/test_unity/test_unity > /dev/null 2>&1
        - cd build
        - mkdir gcov
        - cd gcov
        - gcov -r -p ../src/*.gcno
        # only want coverage data for src and inc folders
        - mkdir tmp
        - mv *.* tmp
        - cd tmp
        - mv ^#^#inc* ../
        - mv ^#^#src* ../
        - rm *
        - cd ../
        - rmdir tmp
        - ls
        - cd ../

        # get blame info for sonar-scanner
        - git fetch --unshallow
        # upload to sonar-scanner
        - cd ../
        - sonar-scanner -Dsonar.login=$SONAR_LOGIN

before_script:
  # install pre-compiled Qt5 binaries & static libraries to $QT5_INSTALL_PREFIX
  # note absolute paths currently hard coded in QT binaries
  # to override this, add a qt.conf file (https://doc.qt.io/qt-5/qt-conf.html#overriding-paths)
  - wget "https://github.com/lkeegan/qt5-static/releases/latest/download/qt5-static-$TRAVIS_OS_NAME.tgz"
  - sudo tar xzvf qt5-static-$TRAVIS_OS_NAME.tgz -C /
  # export path for Qt5 binaries
  - export PATH=$QT5_INSTALL_PREFIX/bin:$PATH
  # download pre-compiled static libSBML (and other) libraries
  - cd ext
  - wget "https://github.com/lkeegan/libsbml-static/releases/latest/download/libsbml-static-$TRAVIS_OS_NAME.tgz"
  - tar xzvf libsbml-static-$TRAVIS_OS_NAME.tgz
  - wget "https://github.com/lkeegan/llvm-static/releases/latest/download/llvm-static-$TRAVIS_OS_NAME.tgz"
  - tar xzvf llvm-static-$TRAVIS_OS_NAME.tgz
  - wget "https://github.com/lkeegan/dune-copasi-static/releases/latest/download/dune-copasi-static-$TRAVIS_OS_NAME.tgz"
  - tar xzvf dune-copasi-static-$TRAVIS_OS_NAME.tgz
  - ls */*
  - cd ..

notifications:
  email: false
deploy:
  # if build is tagged, upload executables to github release
  provider: releases
  api_key:
    secure: E0WtptZea2n40eN+FBYZ2XYv/pjKUjVFZavl8BTVYhidzXYuT/DvhoehPVauJRy/t5QLMtmyd5ww9dhYkIcNcpAc1INrUlYG274D8xgXwbgsftmFbMqdrKR9f/qkynP0r6LCd1p0Tuhxxf37OcTYVEOjbvV+KsTzpWHtS9AqZGvMfv/rpI4r/Zu/LfGBs2T7Rr8Mlfy5YBI2L7lGka3ziTIic01pKDfjHJQ2xD2N366mEqcpB0vjF8c9b+qIUbQ8g8ybLoMfKM6ZSvcpz2NmLQK8l8gzzTN/k1PI2DJxmzi+9G031RXLAXvbR8I8NEQlZfsicepHk0m13EI7x5/TIGaa2ngSgX1W7oAL0IAkJFpcWcN5RQOgowCBAB/UnHCX8EgnBAiD8eTlc4DUC2WY84Dr3EcdhLg0bEX/Ky4mDAxt0QgABG0hEU3kE6USsUvp7IZmnCEdu8e+F/HRmvSUqECI9FvjmpHdBHwIv6anVA2pndN/ZGn4+4BWbo6IwycAh0FPAnvvs6guxnOqQW/eMRgBI3y4grzEYP/bPzlL1W6q42r6fwvh45LtcgC+joAoJCL3I51QcZ1joMY/OShSaKi3MnokImmb/GPRvebe3hDGGSsEAarrmIRb0zCMYDMdHzA+pqeojGZf6SCfIculmeE1MO2t/DqumxQRxTGx+8k=
  file: $DEPLOY_FILE
  skip_cleanup: true
  on:
    repo: lkeegan/spatial-model-editor
    overwrite: true
    tags: true
    all_branches: true
    condition: $DEPLOY_FILE != ""
