# windows release build: MinGW-w64 from msys64, currently gcc 9.1.0 on Windows Server 2012 R2
image:
  - Visual Studio 2015
install:
  - set PATH=C:\msys64\mingw64\bin;%PATH%

before_build:
  - mingw32-make --version
  - g++ --version
  # note absolute paths currently hard coded in QT binaries
  # to override this, add a qt.conf file (https://doc.qt.io/qt-5/qt-conf.html#overriding-paths)
  # install pre-compiled Qt5 binaries & static libraries
  - cd ..
  - mkdir qt5-static
  - cd qt5-static
  - appveyor DownloadFile "https://github.com/lkeegan/qt5-static/releases/latest/download/qt5-static-win32.zip"
  - 7z x qt5-static-win32.zip
  - dir install
  - cd ..\spatial-model-editor
  - dir
  # export path for Qt5 binaries
  - set PATH=C:\projects\qt5-static\install\bin;%PATH%
  - qmake -v
  # build qcustomplot library
  - cd ext\qcustomplot
  - qmake qcustomplot.pro
  - mingw32-make -j2
  - dir
  - dir release
  - mv release/* .
  - dir
  - cd ..\..\
  # build triangle library
  - cd ext\triangle
  - mingw32-make -j2
  - cd ..\..\
  # download pre-compiled static libSBML (and other) libraries
  - cd ext
  - appveyor DownloadFile "https://github.com/lkeegan/libsbml-static/releases/latest/download/libsbml-static-windows.zip"
  - 7z x libsbml-static-windows.zip
  - dir
  - dir libsbml
  - cd ..

build_script:
  # compile and run unit tests
  - mkdir build-tests
  - cd build-tests
  - qmake -Wall -config release ..\test.pro
  - mingw32-make -j2
  - release\test.exe -d=yes
  - cd ..
  # compile release executable
  - mkdir build
  - cd build
  - qmake -Wall -config release ..\spatial-model-editor.pro
  - mingw32-make -j2

artifacts:
  - path: build/release/spatial-model-editor.exe
    name: spatial-model-editor

deploy:
  provider: GitHub
  description: ''
  artifact: spatial-model-editor
  auth_token:
    secure: AzIgTar/Vk7S6hA8HAZAImacEIrbwmfrR6PJ+qHuAQHuLyPSAAcpI5rl/w6BumKp
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
