# windows release build: MinGW-w64 from msys64, currently gcc 9.1.0 on Windows Server 2012 R2
image:
  - Visual Studio 2015
install:
  - set PATH=C:\msys64\usr\bin;%PATH%
# only build master branch (and PRs to master)
branches:
  only:
    - master
before_build:
  # note absolute paths currently hard coded in QT binaries
  # to override this, add a qt.conf file (https://doc.qt.io/qt-5/qt-conf.html#overriding-paths)
  # install pre-compiled Qt5 binaries & static libraries
  - cd ..
  - mkdir qt5-static
  - cd qt5-static
  - appveyor DownloadFile "https://github.com/lkeegan/qt5-static/releases/latest/download/qt5-static-win32.zip"
  - 7z x qt5-static-win32.zip
  - dir install
  - cd ..\spatial-model-editor
  - dir
  # export path for Qt5 binaries
  - set PATH=C:\projects\qt5-static\install\bin;%PATH%
  - qmake -v
  # download pre-compiled static libSBML (and other) libraries
  - cp -r * C:\msys64\home\appveyor\.
  - dir C:\msys64\home\appveyor
  - cd C:\msys64\home\appveyor\ext
  - appveyor DownloadFile "https://github.com/lkeegan/libsbml-static/releases/latest/download/libsbml-static-windows.zip"
  - 7z x libsbml-static-windows.zip
  - appveyor DownloadFile "https://github.com/lkeegan/dune-copasi-static/releases/latest/download/dune-copasi-static-windows.zip"
  - 7z x dune-copasi-static-windows.zip
  - dir
  - dir lib
  - dir include
  - dir dune
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  # compile
  - bash -l ci-build.sh "release optimize_full" mingw32-make
  # run non-gui tests
  - C:\msys64\home\appveyor\build\test\test.exe -as "~[gui]" > test.txt 2>&1 & exit 0
  - ps: Get-Content test.txt -Tail 100
  - rm test.txt
  # run benchmarks (~1 sec per benchmark, ~20secs total)
  # - C:\msys64\home\appveyor\build\benchmark\benchmark.exe 1

  - cp C:\msys64\home\appveyor\build\src\spatial-model-editor.exe %APPVEYOR_BUILD_FOLDER%\.

artifacts:
  - path: spatial-model-editor.exe
    name: spatial-model-editor

deploy:
  provider: GitHub
  description: ''
  artifact: spatial-model-editor
  auth_token:
    secure: AzIgTar/Vk7S6hA8HAZAImacEIrbwmfrR6PJ+qHuAQHuLyPSAAcpI5rl/w6BumKp
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
