name: Code Quality

on: push

defaults:
  run:
    shell: bash

jobs:
  codecov:
    name: Codecov tests coverage
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Cache ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ccache-${{ github.job }}-${{ runner.os }}-${{ github.sha }}
        restore-keys: ccache-${{ github.job }}-${{ runner.os }}-
    - name: Get static libs
      run: sudo ./ci/getlibs.sh linux
    - name: Build script
      run: ./ci/codecov.sh

  sonar:
    name: Sonar static analysis
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0
      - name: Cache ccache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ccache-${{ github.job }}-${{ runner.os }}-${{ github.sha }}
          restore-keys: ccache-${{ github.job }}-${{ runner.os }}-
      - name: Cache sonar
        uses: actions/cache@v2
        with:
          path: ~/.sonarcache
          key: sonar-${{ github.job }}-${{ runner.os }}-${{ github.sha }}
          restore-keys: sonar-${{ github.job }}-${{ runner.os }}-
      - name: Get static libs
        run: sudo ./ci/getlibs.sh linux
      - name: Build script
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./ci/sonar.sh
